### ISSUE TITLE
block-begin/end-regexp?

### ISSUE THREAD

**Issue by andreas-roehler** [andsunds/epoch-mode#5]
AFAIU blocks don't nest in this language. Than you don't need to check for block-end, jumping to beginning and reading the end-formula is enough.

**Comment by TobiasZawada** [comment]
Yes, blocks don't nest in this language. That is exactly the reason **why** I also search for `end:...`.
If the user requests block-closing and we find an `end:...` through a backwards-search that indicates an error condition and we generate a `user-error`.

**Comment by andreas-roehler** [comment]
Well, in the precise case, the question raised here probably doesn't matter. It's just for exercise resp. our fun. In other real cases, complexity is soon an issue and we have to look what is really needed - otherwise maintenance might grow difficult. So: how probable is the user-error to happen? Will the user not notice it by itself?

**Comment by andsunds** [comment]
As far as I'm concerned, I think that generating the user error when a block is already closed is a good idea. It will probably not occur very often since `begin:...` and `end:...` are syntax highlighted. However, I think that the extra complexity in this code is a price worth paying, given that the nature of EPOCH is to be run on large computing clusters, and anything that helps reduce errors in the input `.deck` files is very valuable.

**Comment by andreas-roehler** [comment]
Okay. So lets close this, just wanted to discuss the item. WRT possible errors somethings like Emacs command `check-parens` might be of interest.
